# Generated by Django 5.2.8 on 2025-11-09 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(help_text='Уникальный идентификатор пользователя в Telegram', unique=True, verbose_name='Telegram ID')),
                ('username', models.CharField(blank=True, help_text='Имя пользователя в Telegram (@username)', max_length=255, null=True, verbose_name='Telegram Username')),
                ('first_name', models.CharField(help_text='Имя пользователя из Telegram', max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, help_text='Фамилия пользователя из Telegram', max_length=255, null=True, verbose_name='Фамилия')),
                ('photo_url', models.URLField(blank=True, help_text='URL аватара пользователя в Telegram', max_length=500, null=True, verbose_name='URL фото')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Telegram профиль',
                'verbose_name_plural': 'Telegram профили',
                'db_table': 'telegram_profiles',
                'indexes': [models.Index(fields=['telegram_id'], name='telegram_pr_telegra_c0d5c9_idx'), models.Index(fields=['username'], name='telegram_pr_usernam_a13301_idx')],
            },
        ),
    ]
