# Generated by Django 5.0.6 on 2025-11-21 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_initial_cryptocurrencies'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='cryptocurrency',
            new_name='wallet_cryp_symbol_54ae14_idx',
            old_name='wallet_cryp_symbol__idx',
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='wallet_tran_wallet__abbc5a_idx',
            old_name='wallet_tran_wallet__idx',
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='wallet_tran_transac_019d56_idx',
            old_name='wallet_tran_transac__idx',
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='wallet_tran_tx_hash_510492_idx',
            old_name='wallet_tran_tx_hash_idx',
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='wallet_tran_created_0b36a1_idx',
            old_name='wallet_tran_created__idx',
        ),
        migrations.RenameIndex(
            model_name='wallet',
            new_name='wallet_wall_user_id_083072_idx',
            old_name='wallet_wall_user_id__idx',
        ),
        migrations.RenameIndex(
            model_name='wallet',
            new_name='wallet_wall_address_c7bf63_idx',
            old_name='wallet_wall_address_idx',
        ),
        migrations.RenameIndex(
            model_name='wallet',
            new_name='wallet_wall_created_bd9551_idx',
            old_name='wallet_wall_created__idx',
        ),
    ]
