# Generated by Django 5.0.6 on 2025-11-14 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Название вашего хобби', max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(help_text='Уникальный идентификатор для URL', max_length=200, unique=True, verbose_name='URL-адрес')),
                ('description', models.TextField(blank=True, help_text='Краткое описание хобби', verbose_name='Описание')),
                ('image', models.ImageField(blank=True, help_text='Изображение для хобби', null=True, upload_to='hobbies/', verbose_name='Изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Хобби',
                'verbose_name_plural': 'Хобби',
                'db_table': 'hobbies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('post', 'Пост'), ('note', 'Заметка'), ('thought', 'Рассуждение')], db_index=True, default='post', max_length=10, verbose_name='Тип записи')),
                ('title', models.CharField(help_text='Заголовок записи', max_length=200, verbose_name='Заголовок')),
                ('content', models.TextField(help_text='Текст записи', verbose_name='Содержание')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата обновления')),
                ('hobby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='hobbies.hobby', verbose_name='Хобби')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
                'db_table': 'entries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['hobby', '-created_at'], name='entries_hobby_i_ee4af9_idx'), models.Index(fields=['entry_type', '-created_at'], name='entries_entry_t_652eb7_idx')],
            },
        ),
    ]
