# Generated by Django 5.2.8 on 2025-11-14 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hobbies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Изображение для поста', upload_to='entries/', verbose_name='Изображение')),
                ('caption', models.CharField(blank=True, help_text='Подпись к изображению (необязательно)', max_length=200, verbose_name='Подпись')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, help_text='Порядок отображения изображения (меньше = выше)', verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата добавления')),
            ],
            options={
                'verbose_name': 'Изображение поста',
                'verbose_name_plural': 'Изображения постов',
                'db_table': 'entry_images',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['-created_at'], 'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
        migrations.RemoveIndex(
            model_name='entry',
            name='entries_entry_t_652eb7_idx',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='entry_type',
        ),
        migrations.AlterField(
            model_name='entry',
            name='content',
            field=models.TextField(help_text='Текст поста', verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='title',
            field=models.CharField(help_text='Заголовок поста', max_length=200, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='entryimage',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='hobbies.entry', verbose_name='Пост'),
        ),
    ]
