# Generated by Django 5.2.8 on 2025-11-16 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hobbies', '0002_entryimage_alter_entry_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hobby',
            options={'ordering': ['-created_at'], 'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
        migrations.AlterField(
            model_name='entry',
            name='hobby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='hobbies.hobby', verbose_name='Проект'),
        ),
        migrations.AlterField(
            model_name='hobby',
            name='description',
            field=models.TextField(blank=True, help_text='Краткое описание проекта', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='hobby',
            name='image',
            field=models.ImageField(blank=True, help_text='Изображение для проекта', null=True, upload_to='hobbies/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='hobby',
            name='title',
            field=models.CharField(help_text='Название вашего проекта', max_length=200, verbose_name='Название'),
        ),
    ]
