# Generated by Django 5.0.6 on 2025-11-18 03:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hobbies', '0003_alter_hobby_options_alter_entry_hobby_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='hobby',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hobbies', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='hobby',
            name='slug',
            field=models.SlugField(help_text='Уникальный идентификатор для URL', max_length=200, verbose_name='URL-адрес'),
        ),
        migrations.AddConstraint(
            model_name='hobby',
            constraint=models.UniqueConstraint(fields=('user', 'slug'), name='unique_user_slug'),
        ),
    ]
