# Generated by Django 5.0.6 on 2025-12-27 10:22

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedWorkout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, help_text='Дата проведения тренировки', verbose_name='Дата')),
                ('notes', models.TextField(blank=True, help_text='Дополнительные заметки о тренировке', null=True, verbose_name='Заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Проведенная тренировка',
                'verbose_name_plural': 'Проведенные тренировки',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Например: Отжимания, Подтягивания, Бег', max_length=200, verbose_name='Название упражнения')),
                ('measurement_type', models.CharField(choices=[('reps', 'Повторы/Подходы'), ('time_distance', 'Время и дистанция'), ('weight_reps', 'Вес и повторы')], default='reps', help_text='Как измеряется это упражнение', max_length=20, verbose_name='Тип измерения')),
                ('description', models.TextField(blank=True, help_text='Дополнительное описание упражнения', null=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Упражнение',
                'verbose_name_plural': 'Упражнения',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Например: Утренняя разминка, Силовая тренировка', max_length=200, verbose_name='Название тренировки')),
                ('description', models.TextField(blank=True, help_text='Описание тренировки', null=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Тренировка',
                'verbose_name_plural': 'Тренировки',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CompletedExercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sets', models.PositiveIntegerField(blank=True, help_text='Количество подходов', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Подходы')),
                ('reps', models.PositiveIntegerField(blank=True, help_text='Количество повторов в подходе (или общее количество)', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Повторы')),
                ('duration_minutes', models.PositiveIntegerField(blank=True, help_text='Продолжительность в минутах', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Время (минуты)')),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, help_text='Пройденная дистанция в километрах', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Дистанция (км)')),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, help_text='Использованный вес в килограммах', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Вес (кг)')),
                ('notes', models.TextField(blank=True, help_text='Дополнительные заметки об упражнении', null=True, verbose_name='Заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('completed_workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_exercises', to='workouts.completedworkout', verbose_name='Проведенная тренировка')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_exercises', to='workouts.exercise', verbose_name='Упражнение')),
            ],
            options={
                'verbose_name': 'Выполненное упражнение',
                'verbose_name_plural': 'Выполненные упражнения',
                'ordering': ['completed_workout', 'exercise'],
            },
        ),
        migrations.CreateModel(
            name='WeightEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, help_text='Дата измерения веса', verbose_name='Дата')),
                ('weight_kg', models.DecimalField(decimal_places=2, help_text='Вес тела в килограммах', max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Вес (кг)')),
                ('notes', models.TextField(blank=True, help_text='Дополнительные заметки (например, время измерения, условия)', null=True, verbose_name='Заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Запись веса',
                'verbose_name_plural': 'Записи веса',
                'ordering': ['-date', '-created_at'],
                'unique_together': {('date',)},
            },
        ),
        migrations.AddField(
            model_name='completedworkout',
            name='workout',
            field=models.ForeignKey(help_text='Шаблон тренировки, которая была выполнена', on_delete=django.db.models.deletion.CASCADE, related_name='completed_workouts', to='workouts.workout', verbose_name='Тренировка'),
        ),
        migrations.CreateModel(
            name='WorkoutExercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Порядок выполнения упражнения в тренировке', verbose_name='Порядок')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_exercises', to='workouts.exercise', verbose_name='Упражнение')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_exercises', to='workouts.workout', verbose_name='Тренировка')),
            ],
            options={
                'verbose_name': 'Упражнение в тренировке',
                'verbose_name_plural': 'Упражнения в тренировках',
                'ordering': ['workout', 'order'],
                'unique_together': {('workout', 'exercise')},
            },
        ),
        migrations.AddField(
            model_name='workout',
            name='exercises',
            field=models.ManyToManyField(help_text='Упражнения, входящие в тренировку', related_name='workouts', through='workouts.WorkoutExercise', to='workouts.exercise', verbose_name='Упражнения'),
        ),
    ]
