# Generated by Django 5.0.6 on 2025-12-27 10:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_alter_completedexercise_id_alter_completedworkout_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completedexercise',
            name='reps',
        ),
        migrations.RemoveField(
            model_name='completedexercise',
            name='sets',
        ),
        migrations.RemoveField(
            model_name='completedexercise',
            name='weight_kg',
        ),
        migrations.AddField(
            model_name='workout',
            name='workout_type',
            field=models.CharField(choices=[('strength', 'Силовая'), ('endurance', 'Выносливость'), ('cardio', 'Кардио'), ('flexibility', 'Гибкость'), ('mixed', 'Смешанная'), ('other', 'Другое')], default='mixed', help_text='Тип тренировки: силовая, выносливость, кардио и т.д.', max_length=20, verbose_name='Тип тренировки'),
        ),
        migrations.AlterField(
            model_name='completedexercise',
            name='distance_km',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Пройденная дистанция в километрах (для бега, плавания)', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Дистанция (км)'),
        ),
        migrations.AlterField(
            model_name='completedexercise',
            name='duration_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Продолжительность в минутах (для бега, плавания)', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Время (минуты)'),
        ),
        migrations.CreateModel(
            name='ExerciseSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_number', models.PositiveIntegerField(help_text='Порядковый номер подхода (1, 2, 3...)', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Номер подхода')),
                ('reps', models.PositiveIntegerField(blank=True, help_text='Количество повторений в этом подходе', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Повторы')),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, help_text='Использованный вес в килограммах для этого подхода', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Вес (кг)')),
                ('duration_seconds', models.PositiveIntegerField(blank=True, help_text='Время выполнения подхода в секундах', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Время (секунды)')),
                ('notes', models.TextField(blank=True, help_text='Дополнительные заметки о подходе', null=True, verbose_name='Заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('completed_exercise', models.ForeignKey(help_text='Упражнение, к которому относится этот подход', on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='workouts.completedexercise', verbose_name='Выполненное упражнение')),
            ],
            options={
                'verbose_name': 'Подход',
                'verbose_name_plural': 'Подходы',
                'ordering': ['completed_exercise', 'set_number'],
                'unique_together': {('completed_exercise', 'set_number')},
            },
        ),
    ]
