# Generated by Django 5.0.6 on 2025-12-27 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_remove_completedexercise_reps_and_more'),
    ]

    operations = [
        # Сначала удаляем модели (это автоматически удалит все связанные поля)
        migrations.DeleteModel(
            name='ExerciseSet',
        ),
        migrations.DeleteModel(
            name='CompletedExercise',
        ),
        migrations.DeleteModel(
            name='CompletedWorkout',
        ),
        migrations.DeleteModel(
            name='WorkoutExercise',
        ),
        migrations.DeleteModel(
            name='Workout',
        ),
        migrations.DeleteModel(
            name='Exercise',
        ),
    ]
