# Generated by Django 5.0.6 on 2025-12-27 10:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0004_remove_exerciseset_completed_exercise_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='weightentry',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='weightentry',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Владелец записи веса', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weight_entries', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterUniqueTogether(
            name='weightentry',
            unique_together={('user', 'date')},
        ),
    ]
