# Generated by Django 5.0.6 on 2025-12-27 10:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0006_populate_weightentry_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='weightentry',
            name='user',
            field=models.ForeignKey(
                help_text='Владелец записи веса',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='weight_entries',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Пользователь'
            ),
        ),
    ]

