# Generated by Django 5.0.6 on 2025-12-27 10:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0007_alter_weightentry_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, help_text='Дата проведения тренировки', verbose_name='Дата')),
                ('workout_type', models.CharField(choices=[('strength', 'Силовая'), ('endurance', 'Выносливость'), ('cardio', 'Кардио'), ('flexibility', 'Гибкость'), ('mixed', 'Смешанная'), ('yoga', 'Йога'), ('pilates', 'Пилатес'), ('other', 'Другое')], default='mixed', help_text='Тип тренировки: силовая, выносливость, кардио и т.д.', max_length=20, verbose_name='Тип тренировки')),
                ('notes', models.TextField(blank=True, help_text='Дополнительные заметки о тренировке', null=True, verbose_name='Заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('user', models.ForeignKey(help_text='Владелец тренировки', on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Тренировка',
                'verbose_name_plural': 'Тренировки',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
