# Generated by Django 5.0.6 on 2025-12-27 15:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0008_workout'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='duration_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Продолжительность тренировки в минутах', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Продолжительность (минуты)'),
        ),
    ]
