# Generated by Django 5.0.6 on 2025-11-14 22:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(help_text='Название сайта или сервиса', max_length=200, verbose_name='Сервис')),
                ('login', models.CharField(help_text='Имя пользователя или email для входа', max_length=200, verbose_name='Логин')),
                ('password_encrypted', models.TextField(help_text='Пароль в зашифрованном виде', verbose_name='Пароль (зашифрован)')),
                ('email', models.EmailField(blank=True, help_text='Email адрес (необязательно)', max_length=200, null=True, validators=[django.core.validators.EmailValidator()], verbose_name='Email')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Пароль',
                'verbose_name_plural': 'Пароли',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['service'], name='passwords_p_service_9a96af_idx'), models.Index(fields=['-created_at'], name='passwords_p_created_a91039_idx')],
            },
        ),
    ]
