# Generated by Django 5.0.6 on 2025-11-20 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passwords', '0002_passwordentry_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordentry',
            name='email',
        ),
    ]
